# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I3wlrdtBm1JSJ_YBSoA5rtFnGCWWJat5
"""



#Calculadora

operacao = int(input('Olá, qual operação você deseja realizar hoje? digite o número do tipo da operação ex: 1 = adição, 2 = subtração, 3 = multiplicação ou 4 divisão: '))
numero1 = int(input('Digite seu primeiro número: '))
numero2 = int(input('Digite seu segundo número: '))

if operacao == 1:
  resultado = numero1 + numero2
  print(resultado)
elif operacao == 2:
  resultado = numero1 - numero2
  print(resultado)
elif operacao == 3:
  resultado = numero1 * numero2
  print(resultado)
elif operacao == 4:
  resultado = numero1 / numero2
  print(resultado)